version: "1.0"
info:
  model: int-scaffold
packages:
- name: SpProject
  gitBranch: master
services:
- serviceName: project.sp.integrations:dafstream
  packages:
  - name: SpProject
    version: "1.0"
- serviceName: pub.io:streamToBytes
  packages:
  - name: WmPublic
    version: 12.1.0.0.1206
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 12.1.0.0.1206
- serviceName: pub.string:concat
  packages:
  - name: WmPublic
    version: 12.1.0.0.1206
